import { test, expect } from '@playwright/test';
test('Dropdownbox', async ({ page }) => {
await page.goto('https://rahulshettyacademy.com/AutomationPractice/');
await expect(page).toHaveURL('https://rahulshettyacademy.com/AutomationPractice/');
console.log('main Site reached and verified');
const heading1 =page.getByRole('heading', { name: 'Practice page' });
await expect(heading1).toBeVisible();
console.log('Heading :-Practice page are verified');
const heading2 =page.getByText('Dropdown Example', { exact: true });
await expect(heading2).toBeVisible();
console.log('Heading :-Dropdown Example are verified');
const dropdown = page.locator('select#dropdown-class-example');
await dropdown.click();
await expect(dropdown).toBeVisible();
console.log('Combo box is visible');
await dropdown.click();
await dropdown.selectOption({ value: 'option1' });
await expect(dropdown).toHaveValue('option1');
console.log('Option 1 selected and verified');
await dropdown.selectOption({ index: 2 });
await expect(dropdown).toHaveValue('option2');
console.log('Option 2 selected and verified');
await dropdown.selectOption({ index: 3 });
await expect(dropdown).toHaveValue('option3');
console.log('Option 3 selected and verified');
});