import { test, expect } from '@playwright/test';
test('Just testing', async ({ page }) => {
await page.goto('https://rahulshettyacademy.com/AutomationPractice/');
await expect(page).toHaveURL('https://rahulshettyacademy.com/AutomationPractice/');
console.log('main Site reached and verified');
const heading1 =page.getByRole('heading', { name: 'Practice page' });
await expect(heading1).toBeVisible();
console.log('Heading :-Practice page are verified');
const radioExample = page.getByText('Radio Button Example', { exact: true });
await expect(radioExample).toBeVisible();
console.log('heading2 :-Radio Button Example verified');
const radio1 = page.locator("//input[@value='radio1']");
await radio1.check();
await expect(radio1).toBeChecked();
console.log('radio Button1 verified');
const radio2 = page.locator("//input[@value='radio2']");
await radio2.check();
await expect(radio2).toBeChecked();
console.log('radio Button2 verified');
const radio3 = page.locator("//input[@value='radio3']");
await radio3.check();
await expect(radio3).toBeChecked();
console.log('radio Button3 verified');
});