import { test,expect } from '@playwright/test';
test('Switchtab', async ({ page }) => {
await page.goto('https://rahulshettyacademy.com/AutomationPractice/');
await expect(page).toHaveURL('https://rahulshettyacademy.com/AutomationPractice/');
console.log('main Site reached and verified');
const heading1 =page.getByRole('heading', { name: 'Practice page' });
await expect(heading1).toBeVisible();
console.log('Heading :-Practice page are verified');
const heading2 =await page.getByText('Mouse Hover Example', { exact: true });
await expect(heading2).toBeVisible();
console.log('Heading :-Mouse Hover Example verified ');
const hover = page.getByRole('button', { name: 'Mouse Hover' });
await expect(hover).toBeVisible();
await expect(hover).toBeEnabled();
await hover.hover();
console.log('The button is Visible and enabled');
const Top =await page.getByRole('link', { name: 'Top' });
await expect(Top).toBeVisible();
await Top.click();
console.log('Clicked Top option');
await hover.hover();
const Thereload =await page.getByRole('link', { name: 'Reload' });
await expect(Thereload).toBeVisible();
await Thereload.click();
console.log('Clicked Reload option');
});
